### ISSUE TITLE
Issue in Update Participant

### ISSUE THREAD

**Issue by ShubhamJuIT** [livekit/server-sdk-kotlin#40]
**Describe the bug**
When updating participant level metadata its not updating in meta data rather it is change name of participant.

This was working properly earlier. I guess due to some latest deployment we are facing this issue.

I am using the latest version i.e 0.5.7

I am sending this in request:

{
  "room_": "ID",
  "identity_: "12",
  "metadata_": "NEW META DATA",
  "name_": "Studuent Name",
  "memoizedInitialized": 1
}

In response it is not updating the meta rather it change the name of participant. Here is the response

{
  "sid_": "SID",
  "identity_": "12",
  "state_": 2,
  "metadata_": "OLD META DATA",
  "joinedAt_": timestamp,
  "name_": "NEW META DATA",
  "permission_": "permission"
}

**Comment by davidliu** [comment]
Sounds like you're just passing in the new metadata to the `name` parameters. If you're using kotlin, make sure to use named parameters to avoid this situation. If you're using Java, you'll need to ensure you fill in the fields properly so you don't put things in the wrong order.
