### ISSUE TITLE
serviceClient.sendData can't set topic

### ISSUE THREAD

**Issue by farsunset** [livekit/server-sdk-kotlin#45]
**Is your feature request related to a problem? Please describe.**
serviceClient.sendData can't set topic.

i want set data topic to send. but sendData() has no topic paramter

sdk-version:0.5.7

**Comment by farsunset** [comment]
It is very useful. please support  Thanks

**Comment by farsunset** [comment]
@davidliu

**Comment by davidzhao** [comment]
Please consider opening a PR if this is important to you. We do plan on adding this capability, but there is no ETA at the moment.

**Comment by davidliu** [comment]
Fixed by #67.
