### ISSUE TITLE
Room auto deleted but emptyTimeout is very long.

### ISSUE THREAD

**Issue by farsunset** [livekit/server-sdk-kotlin#46]
**Describe the bug**
`serviceClient.createRoom(roomTag, 31104000,null,null,metadata.toString()); 
`
The 31104000 is second of 365 days, When all member is leaved .
`serviceClient.listRooms(tag) return empty.
` 
**Device Info:**
 - Java Version: [e.g. Java 11]
 - LiveKit Server SDK version: [e.g. 0.5.5]

**Comment by davidzhao** [comment]
related to: https://github.com/livekit/livekit/issues/1776
