### ISSUE TITLE
Missing possibility to configure proxy for EgressServiceClient and IngressServiceClient

### ISSUE THREAD

**Issue by davideberlein** [livekit/server-sdk-kotlin#64]
**Describe the bug**
While the `RoomServiceClient` has received an option to pass in a `okHttpConfigurator: Consumer<OkHttpClient.Builder>` allowing to configure a proxy for the HTTP requests the other two clients: `EgressServiceClient` and `IngressServiceClient` are missing this feature.

**To Reproduce**
Check the constructor of the 3 clients.

**Expected behavior**
`EgressServiceClient` and `IngressServiceClient` should behave the same as `RoomServiceClient`

If you want to I crate a PR for the change.

**Comment by davidliu** [comment]
Fixed by #65.
