### ISSUE TITLE
stopEgress return no response from servers

### ISSUE THREAD

**Issue by shoyu666** [livekit/server-sdk-kotlin#71]
**Describe the bug**
call stopEgress return no response from servers,maybe egress or livekit bug
Why did this problem occur？

**To Reproduce**
just call stopEgress,sometimes return return no response from servers

**Device Info:**
sdk version :io.livekit:livekit-server:0.6.1
egress version:1.8
livekit version:1.7

**Additional context**
https://github.com/livekit/livekit/issues/2362
https://github.com/livekit/egress/issues/739

**Comment by davidzhao** [comment]
Duplicate: https://github.com/livekit/egress/issues/739
