### ISSUE TITLE
Sip endpoints dont seem to work through this client

### ISSUE THREAD

**Issue by jamesmcarthur115555** [livekit/server-sdk-kotlin#82]
**Describe the bug**
Sip endpoints for listing work but the creation ones throw an error

**To Reproduce**
Attempt to create a sip trunk or dispatch rule

{"code":"bad_route","msg":"no handler for path \"/twirp/livekit.Egress/CreateSIPInboundTrunk\"","meta":{"twirp_invalid_route":"POST /twirp/livekit.Egress/CreateSIPInboundTrunk"}}

**Expected behavior**
Creation of tunk or dispatch rule or validation error

**Additional context**

**Comment by jamesmcarthur115555** [comment]
`        LivekitSip.SIPInboundTrunkInfo trunk = null;

        Response<SIPInboundTrunkInfo> tinfo = client.createSipInboundTrunk("testing", Arrays.asList("XXXXXXX"), opts).execute();
        if (tinfo.isSuccessful()) {

            System.out.println("GOOD??");
        } else {
            System.out.println(tinfo.isSuccessful());
            System.out.println(tinfo.errorBody().string());

        }
        `

**Comment by davidliu** [comment]
Fixed by #83
